version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MYSQL_DATABASE
      - ADMIN_PASSWORD
      - CLIENT_ID
      - UID

  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
